export const sample_food = [
  {
    id: 1,
    name: "Pizza",
    price: 12.99,
    cookTime: "10 min",
    favorite: false,
    origins: "Italy",
    stars: 4.5,
    imageUrl: "pizza.png",
    tag: ["Italian", "Fast food", "Pizza"],
  },
  {
    id: 2,
    name: "Burger",
    price: 9.99,
    cookTime: "5 min",
    favorite: false,
    origins: "USA",
    stars: 4.2,
    imageUrl: "burger.png",
    tag: ["American", "Fast food"],
  },
  {
    id: 3,
    name: "Salad",
    price: 6.99,
    cookTime: "3 min",
    favorite: true,
    origins: "Europe",
    stars: 4.8,
    imageUrl: "salad.png",
    tag: ["slow food", "Humburger", "Lunch"],
  },
  {
    id: 4,
    name: "Fries",
    price: 4.99,
    cookTime: "2 min",
    favorite: false,
    origins: "USA",
    stars: 4.1,
    imageUrl: "fries.png",
    tag: ["American", "Fast food", "Lunch"],
  },
  {
    id: 5,
    name: "Pasta",
    price: 10.99,
    cookTime: "15 min",
    favorite: false,
    origins: "Italy",
    stars: 4.7,
    imageUrl: "pasta.png",
    tag: ["Soup", "slow food", "Lunch"],
  },
  {
    id: 6,
    name: "Tacos",
    price: 7.99,
    cookTime: "8 min",
    favorite: false,
    origins: "Mexico",
    stars: 4.6,
    imageUrl: "tacos.png",
    tag: ["Fry", "Fast food", "Pizza"],
  },
];

export const sample_tags = [
  { tag: "All", count: 6 },
  {
    tag: "Fast food",
    count: 4,
  },
  {
    tag: "Pizza",
    count: 2,
  },
  {
    tag: "Lunch",
    count: 3,
  },
  {
    tag: "slow food",
    count: 2,
  },
  {
    tag: "Humburger",
    count: 1,
  },
  {
    tag: "Fry",
    count: 1,
  },
  {
    tag: "Soup",
    count: 1,
  },
];
export const sample_users = [
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    password: "password123",
    address: "123 Main St, City, State, Zip",
    isAdmin: true,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "janesmith@example.com",
    password: "qwerty456",
    address: "456 Elm St, City, State, Zip",
    isAdmin: false,
  },
];
